### ISSUE TITLE
Firewood mod have conflict with StrawMe mod

### ISSUE THREAD

**Issue by Luki-eL** [Royal-Modding/FS19_Firewood#1]
there is a conflict between Firewood mod and StrawMe mod ,hen they are together, you cannot sell prepared firewood and there are no prices at collection points.

StrawMe mod:
https://www.farming-simulator.com/mod.php?lang=en&country=us&mod_id=177412&title=fs2019

![fsScreen_2021_02_28_16_01_06](https://user-images.githubusercontent.com/79857951/109521000-1e3a4c00-7aad-11eb-9992-8ae9430d3cfd.png)

**Comment by fcelsa** [comment]
maybe too many fruitType registered

**Comment by Luki-eL** [comment]
no, it doesn't depend on maps and seasons

**Comment by fcelsa** [comment]
Thanks for your report, we have found time to investigate about issue, we have added a workaround to avoid the problems.
Now both mods can work together; to be honest, the problems came from StrawMe.
Feel free to download the updated version from [here](https://github.com/Royal-Modding/FS19_Firewood/releases/tag/1.1.0.0-RC1)

**Comment by Luki-eL** [comment]
It's great, I'll be testing. If you need a tester and / or translator (Polish), I can help. Let me know by e-mail lukasz.lacina @ gmail.com
