### ISSUE TITLE
mod conflict with beetharvest mod, no firewood additions to salepoints

### ISSUE THREAD

**Issue by sashaman** [Royal-Modding/FS19_Firewood#5]
with beetharvest mod active, no firewood is added to any salepoint
i dont know why, might also be an issue of beetharvest, i let w33zl know about so he can look into it as well

**Comment by fcelsa** [comment]
Work for me.
![Immagine 2021-04-29 220822](https://user-images.githubusercontent.com/4340190/116613049-846e0e80-a938-11eb-9517-d75e5eb852bd.png)

**Comment by fcelsa** [comment]
Appear to be same problem happen with StrawMe mod that use appendedFunction in wrong way, maybe @sashaman have not patched version, try this RC release:
https://github.com/Royal-Modding/FS19_Firewood/releases/tag/1.1.0.0-RC1

**Comment by sashaman** [comment]
indeed, i completely missed that one - thanks a lot for pointing out!
